#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure Nginx so that its HTTP response contains
# a custom header

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 153837-web-01 100.25.150.172 check\n\tserver 153837-web-02 52.72.27.238 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
